/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        /* Primitive brand tokens — from the MK Productions logo */
        brand: {
          DEFAULT: "#FFCC01", // logo yellow
          light: "#FFDB4D",
          dark: "#E6B800",
          deep: "#CCA300",
        },
        /* Gray scale derived from logo gray #727270 */
        steel: {
          50: "#F6F6F4",
          100: "#EDEDEB",
          200: "#DEDEDB",
          300: "#C2C2BF",
          400: "#9C9C99",
          500: "#727270", // logo gray
          600: "#5C5C5A",
          700: "#464645",
          800: "#323231",
          900: "#232322",
          950: "#181817",
          DEFAULT: "#727270",
          light: "#9C9C99",
        },
        "on-error": "#690005",
        background: "#131313",
        "surface-bright": "#393939",
        "on-background": "#e5e2e1",
        "secondary-fixed-dim": "#c6c6c7",
        primary: "#c9c6c5",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#7b7979",
        "inverse-surface": "#e5e2e1",
        "primary-fixed": "#e5e2e1",
        "on-tertiary-fixed-variant": "#484645",
        "surface-dim": "#131313",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#454747",
        "tertiary-fixed-dim": "#cac6c3",
        error: "#ffb4ab",
        "surface-container-highest": "#353535",
        "on-primary": "#313030",
        "on-tertiary-fixed": "#1d1b1a",
        "on-secondary-fixed": "#1a1c1c",
        "outline-variant": "#444748",
        surface: "#131313",
        "on-primary-fixed": "#1c1b1b",
        "on-tertiary-container": "#7c7977",
        "on-secondary-container": "#b4b5b5",
        "secondary-container": "#454747",
        "primary-container": "#0a0a0a",
        outline: "#8e9192",
        "primary-fixed-dim": "#c9c6c5",
        "surface-container-low": "#1b1b1c",
        "tertiary-fixed": "#e6e1df",
        "surface-tint": "#c9c6c5",
        "on-secondary": "#2f3131",
        "surface-container-high": "#2a2a2a",
        "on-primary-fixed-variant": "#474646",
        secondary: "#c6c6c7",
        "surface-container-lowest": "#0e0e0e",
        "on-surface-variant": "#c4c7c7",
        "secondary-fixed": "#e2e2e2",
        "inverse-primary": "#5f5e5e",
        "surface-container": "#202020",
        "on-surface": "#e5e2e1",
        "surface-variant": "#353535",
        "on-tertiary": "#32302f",
        tertiary: "#cac6c3",
        "inverse-on-surface": "#303030",
        "tertiary-container": "#0b0a09",
      },
      spacing: {
        "margin-mobile": "24px",
        "margin-desktop": "64px",
        unit: "8px",
        "container-max": "1440px",
        gutter: "32px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        display: ["Archivo", "ui-sans-serif", "system-ui", "sans-serif"],
        sans: ["Manrope", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["Archivo", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "display-lg-mobile": ["Archivo", "sans-serif"],
        "label-sm": ["Manrope", "sans-serif"],
        "headline-lg": ["Archivo", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "display-lg": ["Archivo", "sans-serif"],
        "headline-md": ["Archivo", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg-mobile": [
          "48px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" },
        ],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": [
          "80px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
